development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: medgurus_db
  pool: 15
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: medgurus_test
  pool: 15
  username: root
  password:
